name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove containerd if installed
        run: |
          sudo apt-get remove -y containerd || true

      - name: Install containerd.io
        run: |
          sudo apt-get update
          sudo apt-get install -y containerd.io

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/madcamp4_backend:latest --push .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
        with:
          version: 'latest'

      - name: Create Pull Request
        run: |
          gh pr create --base main --head feature-branch --title "Automated PR" --body "This PR was created automatically by GitHub Actions."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
