name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때 실행됩니다.
  pull_request:
    branches:
      - main  # 'main' 브랜치에 대한 풀 리퀘스트가 열릴 때 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin  # 사용할 JDK 배포판

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/madcamp4_backend:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/madcamp4_backend:${{ github.sha }}

      - name: Clean up
        run: docker system prune -af
